//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENDA_YHM.FerreteriaServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DBMensajes", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSucursalLMO")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.FerreteriaServiceRef.tblProducto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.FerreteriaServiceRef.tblUsuarios))]
    public partial class DBMensajes : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeCorrectoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeCorrecto {
            get {
                return this.MensajeCorrectoField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeCorrectoField, value) != true)) {
                    this.MensajeCorrectoField = value;
                    this.RaisePropertyChanged("MensajeCorrecto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblProducto", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSucursalLMO")]
    [System.SerializableAttribute()]
    public partial class tblProducto : TIENDA_YHM.FerreteriaServiceRef.DBMensajes {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int bitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int bitEstatus {
            get {
                return this.bitEstatusField;
            }
            set {
                if ((this.bitEstatusField.Equals(value) != true)) {
                    this.bitEstatusField = value;
                    this.RaisePropertyChanged("bitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCantidad {
            get {
                return this.intCantidadField;
            }
            set {
                if ((this.intCantidadField.Equals(value) != true)) {
                    this.intCantidadField = value;
                    this.RaisePropertyChanged("intCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProducto {
            get {
                return this.strProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.strProductoField, value) != true)) {
                    this.strProductoField = value;
                    this.RaisePropertyChanged("strProducto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblUsuarios", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceSucursalLMO")]
    [System.SerializableAttribute()]
    public partial class tblUsuarios : TIENDA_YHM.FerreteriaServiceRef.DBMensajes {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dteFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dteFechaRegistro {
            get {
                return this.dteFechaRegistroField;
            }
            set {
                if ((this.dteFechaRegistroField.Equals(value) != true)) {
                    this.dteFechaRegistroField = value;
                    this.RaisePropertyChanged("dteFechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPass {
            get {
                return this.strPassField;
            }
            set {
                if ((object.ReferenceEquals(this.strPassField, value) != true)) {
                    this.strPassField = value;
                    this.RaisePropertyChanged("strPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuario {
            get {
                return this.strUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioField, value) != true)) {
                    this.strUsuarioField = value;
                    this.RaisePropertyChanged("strUsuario");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FerreteriaServiceRef.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        TIENDA_YHM.FerreteriaServiceRef.tblUsuarios Login(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Login", ReplyAction="http://tempuri.org/IService1/LoginResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblUsuarios> LoginAsync(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProducto", ReplyAction="http://tempuri.org/IService1/RegistrarProductoResponse")]
        TIENDA_YHM.FerreteriaServiceRef.tblProducto RegistrarProducto(string producto, int sucursal, int cantidad, int categoria, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegistrarProducto", ReplyAction="http://tempuri.org/IService1/RegistrarProductoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> RegistrarProductoAsync(string producto, int sucursal, int cantidad, int categoria, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoSucursal", ReplyAction="http://tempuri.org/IService1/ListadoSucursalResponse")]
        System.Data.DataSet ListadoSucursal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoSucursal", ReplyAction="http://tempuri.org/IService1/ListadoSucursalResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoSucursalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoCategorias", ReplyAction="http://tempuri.org/IService1/ListadoCategoriasResponse")]
        System.Data.DataSet ListadoCategorias();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ListadoCategorias", ReplyAction="http://tempuri.org/IService1/ListadoCategoriasResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> ListadoCategoriasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargarDatosTabla", ReplyAction="http://tempuri.org/IService1/CargarDatosTablaResponse")]
        System.Data.DataSet CargarDatosTabla();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargarDatosTabla", ReplyAction="http://tempuri.org/IService1/CargarDatosTablaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> CargarDatosTablaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        TIENDA_YHM.FerreteriaServiceRef.tblProducto ActualizarProducto(int id, string producto, int sucursal, int cantidad, int categoria, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ActualizarProducto", ReplyAction="http://tempuri.org/IService1/ActualizarProductoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> ActualizarProductoAsync(int id, string producto, int sucursal, int cantidad, int categoria, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarProducto", ReplyAction="http://tempuri.org/IService1/EliminarProductoResponse")]
        TIENDA_YHM.FerreteriaServiceRef.tblProducto EliminarProducto(int id, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EliminarProducto", ReplyAction="http://tempuri.org/IService1/EliminarProductoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> EliminarProductoAsync(int id, int estatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargarDatosBitacora", ReplyAction="http://tempuri.org/IService1/CargarDatosBitacoraResponse")]
        System.Data.DataSet CargarDatosBitacora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CargarDatosBitacora", ReplyAction="http://tempuri.org/IService1/CargarDatosBitacoraResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> CargarDatosBitacoraAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TIENDA_YHM.FerreteriaServiceRef.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TIENDA_YHM.FerreteriaServiceRef.IService1>, TIENDA_YHM.FerreteriaServiceRef.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TIENDA_YHM.FerreteriaServiceRef.tblUsuarios Login(string usuario, string pass) {
            return base.Channel.Login(usuario, pass);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblUsuarios> LoginAsync(string usuario, string pass) {
            return base.Channel.LoginAsync(usuario, pass);
        }
        
        public TIENDA_YHM.FerreteriaServiceRef.tblProducto RegistrarProducto(string producto, int sucursal, int cantidad, int categoria, int estatus) {
            return base.Channel.RegistrarProducto(producto, sucursal, cantidad, categoria, estatus);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> RegistrarProductoAsync(string producto, int sucursal, int cantidad, int categoria, int estatus) {
            return base.Channel.RegistrarProductoAsync(producto, sucursal, cantidad, categoria, estatus);
        }
        
        public System.Data.DataSet ListadoSucursal() {
            return base.Channel.ListadoSucursal();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoSucursalAsync() {
            return base.Channel.ListadoSucursalAsync();
        }
        
        public System.Data.DataSet ListadoCategorias() {
            return base.Channel.ListadoCategorias();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> ListadoCategoriasAsync() {
            return base.Channel.ListadoCategoriasAsync();
        }
        
        public System.Data.DataSet CargarDatosTabla() {
            return base.Channel.CargarDatosTabla();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CargarDatosTablaAsync() {
            return base.Channel.CargarDatosTablaAsync();
        }
        
        public TIENDA_YHM.FerreteriaServiceRef.tblProducto ActualizarProducto(int id, string producto, int sucursal, int cantidad, int categoria, int estatus) {
            return base.Channel.ActualizarProducto(id, producto, sucursal, cantidad, categoria, estatus);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> ActualizarProductoAsync(int id, string producto, int sucursal, int cantidad, int categoria, int estatus) {
            return base.Channel.ActualizarProductoAsync(id, producto, sucursal, cantidad, categoria, estatus);
        }
        
        public TIENDA_YHM.FerreteriaServiceRef.tblProducto EliminarProducto(int id, int estatus) {
            return base.Channel.EliminarProducto(id, estatus);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.FerreteriaServiceRef.tblProducto> EliminarProductoAsync(int id, int estatus) {
            return base.Channel.EliminarProductoAsync(id, estatus);
        }
        
        public System.Data.DataSet CargarDatosBitacora() {
            return base.Channel.CargarDatosBitacora();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> CargarDatosBitacoraAsync() {
            return base.Channel.CargarDatosBitacoraAsync();
        }
    }
}
