//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENDA_YHM.SucursalServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Mensaje", Namespace="http://schemas.datacontract.org/2004/07/SucursalWCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.SucursalServiceRef.Producto))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.SucursalServiceRef.Categoria))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.SucursalServiceRef.Usuario))]
    public partial class Mensaje : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BanErroresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BanErrores {
            get {
                return this.BanErroresField;
            }
            set {
                if ((this.BanErroresField.Equals(value) != true)) {
                    this.BanErroresField = value;
                    this.RaisePropertyChanged("BanErrores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensajes {
            get {
                return this.MensajesField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajesField, value) != true)) {
                    this.MensajesField = value;
                    this.RaisePropertyChanged("Mensajes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/SucursalWCF")]
    [System.SerializableAttribute()]
    public partial class Producto : TIENDA_YHM.SucursalServiceRef.Mensaje {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IntCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BitEstatus {
            get {
                return this.BitEstatusField;
            }
            set {
                if ((this.BitEstatusField.Equals(value) != true)) {
                    this.BitEstatusField = value;
                    this.RaisePropertyChanged("BitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IntCantidad {
            get {
                return this.IntCantidadField;
            }
            set {
                if ((this.IntCantidadField.Equals(value) != true)) {
                    this.IntCantidadField = value;
                    this.RaisePropertyChanged("IntCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrProducto {
            get {
                return this.StrProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.StrProductoField, value) != true)) {
                    this.StrProductoField = value;
                    this.RaisePropertyChanged("StrProducto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Categoria", Namespace="http://schemas.datacontract.org/2004/07/SucursalWCF")]
    [System.SerializableAttribute()]
    public partial class Categoria : TIENDA_YHM.SucursalServiceRef.Mensaje {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrCategoriaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BitEstatus {
            get {
                return this.BitEstatusField;
            }
            set {
                if ((this.BitEstatusField.Equals(value) != true)) {
                    this.BitEstatusField = value;
                    this.RaisePropertyChanged("BitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrCategoria {
            get {
                return this.StrCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.StrCategoriaField, value) != true)) {
                    this.StrCategoriaField = value;
                    this.RaisePropertyChanged("StrCategoria");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/SucursalWCF")]
    [System.SerializableAttribute()]
    public partial class Usuario : TIENDA_YHM.SucursalServiceRef.Mensaje {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DteFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StrUsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BitEstatus {
            get {
                return this.BitEstatusField;
            }
            set {
                if ((this.BitEstatusField.Equals(value) != true)) {
                    this.BitEstatusField = value;
                    this.RaisePropertyChanged("BitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DteFechaRegistro {
            get {
                return this.DteFechaRegistroField;
            }
            set {
                if ((this.DteFechaRegistroField.Equals(value) != true)) {
                    this.DteFechaRegistroField = value;
                    this.RaisePropertyChanged("DteFechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrPass {
            get {
                return this.StrPassField;
            }
            set {
                if ((object.ReferenceEquals(this.StrPassField, value) != true)) {
                    this.StrPassField = value;
                    this.RaisePropertyChanged("StrPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StrUsuario {
            get {
                return this.StrUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.StrUsuarioField, value) != true)) {
                    this.StrUsuarioField = value;
                    this.RaisePropertyChanged("StrUsuario");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SucursalServiceRef.IWCFSucursal")]
    public interface IWCFSucursal {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetUsuario", ReplyAction="http://tempuri.org/IWCFSucursal/GetUsuarioResponse")]
        TIENDA_YHM.SucursalServiceRef.Usuario GetUsuario(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetUsuario", ReplyAction="http://tempuri.org/IWCFSucursal/GetUsuarioResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.SucursalServiceRef.Usuario> GetUsuarioAsync(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetProducto", ReplyAction="http://tempuri.org/IWCFSucursal/GetProductoResponse")]
        System.Data.DataSet GetProducto(string prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetProducto", ReplyAction="http://tempuri.org/IWCFSucursal/GetProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetProductoAsync(string prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/GetCategoriaResponse")]
        System.Data.DataSet GetCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/GetCategoriaResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/InsertarProdcuto", ReplyAction="http://tempuri.org/IWCFSucursal/InsertarProdcutoResponse")]
        int InsertarProdcuto(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/InsertarProdcuto", ReplyAction="http://tempuri.org/IWCFSucursal/InsertarProdcutoResponse")]
        System.Threading.Tasks.Task<int> InsertarProdcutoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/EditarProducto", ReplyAction="http://tempuri.org/IWCFSucursal/EditarProductoResponse")]
        int EditarProducto(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/EditarProducto", ReplyAction="http://tempuri.org/IWCFSucursal/EditarProductoResponse")]
        System.Threading.Tasks.Task<int> EditarProductoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/ElimiarProdcuto", ReplyAction="http://tempuri.org/IWCFSucursal/ElimiarProdcutoResponse")]
        int ElimiarProdcuto(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/ElimiarProdcuto", ReplyAction="http://tempuri.org/IWCFSucursal/ElimiarProdcutoResponse")]
        System.Threading.Tasks.Task<int> ElimiarProdcutoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/InsertarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/InsertarCategoriaResponse")]
        int InsertarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/InsertarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/InsertarCategoriaResponse")]
        System.Threading.Tasks.Task<int> InsertarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/EditarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/EditarCategoriaResponse")]
        int EditarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/EditarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/EditarCategoriaResponse")]
        System.Threading.Tasks.Task<int> EditarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/ElimiarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/ElimiarCategoriaResponse")]
        int ElimiarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/ElimiarCategoria", ReplyAction="http://tempuri.org/IWCFSucursal/ElimiarCategoriaResponse")]
        System.Threading.Tasks.Task<int> ElimiarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/RegistrarUsuario", ReplyAction="http://tempuri.org/IWCFSucursal/RegistrarUsuarioResponse")]
        int RegistrarUsuario(TIENDA_YHM.SucursalServiceRef.Usuario us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/RegistrarUsuario", ReplyAction="http://tempuri.org/IWCFSucursal/RegistrarUsuarioResponse")]
        System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(TIENDA_YHM.SucursalServiceRef.Usuario us);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetSucursal", ReplyAction="http://tempuri.org/IWCFSucursal/GetSucursalResponse")]
        System.Data.DataSet GetSucursal();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/GetSucursal", ReplyAction="http://tempuri.org/IWCFSucursal/GetSucursalResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetSucursalAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/MostrarProducto", ReplyAction="http://tempuri.org/IWCFSucursal/MostrarProductoResponse")]
        System.Data.DataSet MostrarProducto();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/MostrarProducto", ReplyAction="http://tempuri.org/IWCFSucursal/MostrarProductoResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> MostrarProductoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/MostrarBitacora", ReplyAction="http://tempuri.org/IWCFSucursal/MostrarBitacoraResponse")]
        System.Data.DataSet MostrarBitacora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWCFSucursal/MostrarBitacora", ReplyAction="http://tempuri.org/IWCFSucursal/MostrarBitacoraResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> MostrarBitacoraAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWCFSucursalChannel : TIENDA_YHM.SucursalServiceRef.IWCFSucursal, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WCFSucursalClient : System.ServiceModel.ClientBase<TIENDA_YHM.SucursalServiceRef.IWCFSucursal>, TIENDA_YHM.SucursalServiceRef.IWCFSucursal {
        
        public WCFSucursalClient() {
        }
        
        public WCFSucursalClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WCFSucursalClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSucursalClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WCFSucursalClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TIENDA_YHM.SucursalServiceRef.Usuario GetUsuario(string usuario, string pass) {
            return base.Channel.GetUsuario(usuario, pass);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.SucursalServiceRef.Usuario> GetUsuarioAsync(string usuario, string pass) {
            return base.Channel.GetUsuarioAsync(usuario, pass);
        }
        
        public System.Data.DataSet GetProducto(string prod) {
            return base.Channel.GetProducto(prod);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetProductoAsync(string prod) {
            return base.Channel.GetProductoAsync(prod);
        }
        
        public System.Data.DataSet GetCategoria() {
            return base.Channel.GetCategoria();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetCategoriaAsync() {
            return base.Channel.GetCategoriaAsync();
        }
        
        public int InsertarProdcuto(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.InsertarProdcuto(prod);
        }
        
        public System.Threading.Tasks.Task<int> InsertarProdcutoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.InsertarProdcutoAsync(prod);
        }
        
        public int EditarProducto(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.EditarProducto(prod);
        }
        
        public System.Threading.Tasks.Task<int> EditarProductoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.EditarProductoAsync(prod);
        }
        
        public int ElimiarProdcuto(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.ElimiarProdcuto(prod);
        }
        
        public System.Threading.Tasks.Task<int> ElimiarProdcutoAsync(TIENDA_YHM.SucursalServiceRef.Producto prod) {
            return base.Channel.ElimiarProdcutoAsync(prod);
        }
        
        public int InsertarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.InsertarCategoria(cat);
        }
        
        public System.Threading.Tasks.Task<int> InsertarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.InsertarCategoriaAsync(cat);
        }
        
        public int EditarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.EditarCategoria(cat);
        }
        
        public System.Threading.Tasks.Task<int> EditarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.EditarCategoriaAsync(cat);
        }
        
        public int ElimiarCategoria(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.ElimiarCategoria(cat);
        }
        
        public System.Threading.Tasks.Task<int> ElimiarCategoriaAsync(TIENDA_YHM.SucursalServiceRef.Categoria cat) {
            return base.Channel.ElimiarCategoriaAsync(cat);
        }
        
        public int RegistrarUsuario(TIENDA_YHM.SucursalServiceRef.Usuario us) {
            return base.Channel.RegistrarUsuario(us);
        }
        
        public System.Threading.Tasks.Task<int> RegistrarUsuarioAsync(TIENDA_YHM.SucursalServiceRef.Usuario us) {
            return base.Channel.RegistrarUsuarioAsync(us);
        }
        
        public System.Data.DataSet GetSucursal() {
            return base.Channel.GetSucursal();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetSucursalAsync() {
            return base.Channel.GetSucursalAsync();
        }
        
        public System.Data.DataSet MostrarProducto() {
            return base.Channel.MostrarProducto();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MostrarProductoAsync() {
            return base.Channel.MostrarProductoAsync();
        }
        
        public System.Data.DataSet MostrarBitacora() {
            return base.Channel.MostrarBitacora();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> MostrarBitacoraAsync() {
            return base.Channel.MostrarBitacoraAsync();
        }
    }
}
