//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENDA_YHM.Carlos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblProducto", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblProducto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int intCantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitEstatus {
            get {
                return this.bitEstatusField;
            }
            set {
                if ((this.bitEstatusField.Equals(value) != true)) {
                    this.bitEstatusField = value;
                    this.RaisePropertyChanged("bitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idCategoria {
            get {
                return this.idCategoriaField;
            }
            set {
                if ((this.idCategoriaField.Equals(value) != true)) {
                    this.idCategoriaField = value;
                    this.RaisePropertyChanged("idCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int intCantidad {
            get {
                return this.intCantidadField;
            }
            set {
                if ((this.intCantidadField.Equals(value) != true)) {
                    this.intCantidadField = value;
                    this.RaisePropertyChanged("intCantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCategoria {
            get {
                return this.strCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.strCategoriaField, value) != true)) {
                    this.strCategoriaField = value;
                    this.RaisePropertyChanged("strCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProducto {
            get {
                return this.strProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.strProductoField, value) != true)) {
                    this.strProductoField = value;
                    this.RaisePropertyChanged("strProducto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblUsuarios", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblUsuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitAdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dteFechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitAdministrador {
            get {
                return this.bitAdministradorField;
            }
            set {
                if ((this.bitAdministradorField.Equals(value) != true)) {
                    this.bitAdministradorField = value;
                    this.RaisePropertyChanged("bitAdministrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitEstatus {
            get {
                return this.bitEstatusField;
            }
            set {
                if ((this.bitEstatusField.Equals(value) != true)) {
                    this.bitEstatusField = value;
                    this.RaisePropertyChanged("bitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dteFechaRegistro {
            get {
                return this.dteFechaRegistroField;
            }
            set {
                if ((this.dteFechaRegistroField.Equals(value) != true)) {
                    this.dteFechaRegistroField = value;
                    this.RaisePropertyChanged("dteFechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strPass {
            get {
                return this.strPassField;
            }
            set {
                if ((object.ReferenceEquals(this.strPassField, value) != true)) {
                    this.strPassField = value;
                    this.RaisePropertyChanged("strPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuario {
            get {
                return this.strUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioField, value) != true)) {
                    this.strUsuarioField = value;
                    this.RaisePropertyChanged("strUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="catCategoria", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class catCategoria : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCategoriaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitEstatus {
            get {
                return this.bitEstatusField;
            }
            set {
                if ((this.bitEstatusField.Equals(value) != true)) {
                    this.bitEstatusField = value;
                    this.RaisePropertyChanged("bitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idSucursal {
            get {
                return this.idSucursalField;
            }
            set {
                if ((this.idSucursalField.Equals(value) != true)) {
                    this.idSucursalField = value;
                    this.RaisePropertyChanged("idSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCategoria {
            get {
                return this.strCategoriaField;
            }
            set {
                if ((object.ReferenceEquals(this.strCategoriaField, value) != true)) {
                    this.strCategoriaField = value;
                    this.RaisePropertyChanged("strCategoria");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="catAccion", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class catAccion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombre {
            get {
                return this.strNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombreField, value) != true)) {
                    this.strNombreField = value;
                    this.RaisePropertyChanged("strNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblbitacora", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblbitacora : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dteFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCategoriaNuevoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCategoriaViejoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProductoNuevoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strProductoViejoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUserField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dteFecha {
            get {
                return this.dteFechaField;
            }
            set {
                if ((this.dteFechaField.Equals(value) != true)) {
                    this.dteFechaField = value;
                    this.RaisePropertyChanged("dteFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                if ((this.idAccionField.Equals(value) != true)) {
                    this.idAccionField = value;
                    this.RaisePropertyChanged("idAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strAccion {
            get {
                return this.strAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.strAccionField, value) != true)) {
                    this.strAccionField = value;
                    this.RaisePropertyChanged("strAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCategoriaNuevo {
            get {
                return this.strCategoriaNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.strCategoriaNuevoField, value) != true)) {
                    this.strCategoriaNuevoField = value;
                    this.RaisePropertyChanged("strCategoriaNuevo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCategoriaViejo {
            get {
                return this.strCategoriaViejoField;
            }
            set {
                if ((object.ReferenceEquals(this.strCategoriaViejoField, value) != true)) {
                    this.strCategoriaViejoField = value;
                    this.RaisePropertyChanged("strCategoriaViejo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProductoNuevo {
            get {
                return this.strProductoNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.strProductoNuevoField, value) != true)) {
                    this.strProductoNuevoField = value;
                    this.RaisePropertyChanged("strProductoNuevo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strProductoViejo {
            get {
                return this.strProductoViejoField;
            }
            set {
                if ((object.ReferenceEquals(this.strProductoViejoField, value) != true)) {
                    this.strProductoViejoField = value;
                    this.RaisePropertyChanged("strProductoViejo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUser {
            get {
                return this.strUserField;
            }
            set {
                if ((object.ReferenceEquals(this.strUserField, value) != true)) {
                    this.strUserField = value;
                    this.RaisePropertyChanged("strUser");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblBitacorasUsuarios", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblBitacorasUsuarios : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool bitCambioPassField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dteFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioNuevoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioViejoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool bitCambioPass {
            get {
                return this.bitCambioPassField;
            }
            set {
                if ((this.bitCambioPassField.Equals(value) != true)) {
                    this.bitCambioPassField = value;
                    this.RaisePropertyChanged("bitCambioPass");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dteFecha {
            get {
                return this.dteFechaField;
            }
            set {
                if ((this.dteFechaField.Equals(value) != true)) {
                    this.dteFechaField = value;
                    this.RaisePropertyChanged("dteFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                if ((this.idAccionField.Equals(value) != true)) {
                    this.idAccionField = value;
                    this.RaisePropertyChanged("idAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strAccion {
            get {
                return this.strAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.strAccionField, value) != true)) {
                    this.strAccionField = value;
                    this.RaisePropertyChanged("strAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuario {
            get {
                return this.strUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioField, value) != true)) {
                    this.strUsuarioField = value;
                    this.RaisePropertyChanged("strUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuarioNuevo {
            get {
                return this.strUsuarioNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioNuevoField, value) != true)) {
                    this.strUsuarioNuevoField = value;
                    this.RaisePropertyChanged("strUsuarioNuevo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuarioViejo {
            get {
                return this.strUsuarioViejoField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioViejoField, value) != true)) {
                    this.strUsuarioViejoField = value;
                    this.RaisePropertyChanged("strUsuarioViejo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblBitacorasCatalogos", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblBitacorasCatalogos : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dteFechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strAccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCatalogoNuevoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strCatalogoViejoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strUsuarioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dteFecha {
            get {
                return this.dteFechaField;
            }
            set {
                if ((this.dteFechaField.Equals(value) != true)) {
                    this.dteFechaField = value;
                    this.RaisePropertyChanged("dteFecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idAccion {
            get {
                return this.idAccionField;
            }
            set {
                if ((this.idAccionField.Equals(value) != true)) {
                    this.idAccionField = value;
                    this.RaisePropertyChanged("idAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                if ((this.idUsuarioField.Equals(value) != true)) {
                    this.idUsuarioField = value;
                    this.RaisePropertyChanged("idUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strAccion {
            get {
                return this.strAccionField;
            }
            set {
                if ((object.ReferenceEquals(this.strAccionField, value) != true)) {
                    this.strAccionField = value;
                    this.RaisePropertyChanged("strAccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCatalogoNuevo {
            get {
                return this.strCatalogoNuevoField;
            }
            set {
                if ((object.ReferenceEquals(this.strCatalogoNuevoField, value) != true)) {
                    this.strCatalogoNuevoField = value;
                    this.RaisePropertyChanged("strCatalogoNuevo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strCatalogoViejo {
            get {
                return this.strCatalogoViejoField;
            }
            set {
                if ((object.ReferenceEquals(this.strCatalogoViejoField, value) != true)) {
                    this.strCatalogoViejoField = value;
                    this.RaisePropertyChanged("strCatalogoViejo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strUsuario {
            get {
                return this.strUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.strUsuarioField, value) != true)) {
                    this.strUsuarioField = value;
                    this.RaisePropertyChanged("strUsuario");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tblSucursal", Namespace="http://schemas.datacontract.org/2004/07/WCF.ServiciosSurcursales.Server")]
    [System.SerializableAttribute()]
    public partial class tblSucursal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strNombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string strNombre {
            get {
                return this.strNombreField;
            }
            set {
                if ((object.ReferenceEquals(this.strNombreField, value) != true)) {
                    this.strNombreField = value;
                    this.RaisePropertyChanged("strNombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Carlos.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductos", ReplyAction="http://tempuri.org/IService1/consultarProductosResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductos", ReplyAction="http://tempuri.org/IService1/consultarProductosResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosNombre", ReplyAction="http://tempuri.org/IService1/consultarProductosNombreResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductosNombre(string _nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosNombre", ReplyAction="http://tempuri.org/IService1/consultarProductosNombreResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosNombreAsync(string _nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosCategoria", ReplyAction="http://tempuri.org/IService1/consultarProductosCategoriaResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductosCategoria(int _categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosCategoria", ReplyAction="http://tempuri.org/IService1/consultarProductosCategoriaResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosCategoriaAsync(int _categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarUsuario", ReplyAction="http://tempuri.org/IService1/consultarUsuarioResponse")]
        TIENDA_YHM.Carlos.tblUsuarios[] consultarUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarUsuario", ReplyAction="http://tempuri.org/IService1/consultarUsuarioResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblUsuarios[]> consultarUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarCategoria", ReplyAction="http://tempuri.org/IService1/consultarCategoriaResponse")]
        TIENDA_YHM.Carlos.catCategoria[] consultarCategoria();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarCategoria", ReplyAction="http://tempuri.org/IService1/consultarCategoriaResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catCategoria[]> consultarCategoriaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarCategoriaCombo", ReplyAction="http://tempuri.org/IService1/consultarCategoriaComboResponse")]
        TIENDA_YHM.Carlos.catCategoria[] consultarCategoriaCombo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarCategoriaCombo", ReplyAction="http://tempuri.org/IService1/consultarCategoriaComboResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catCategoria[]> consultarCategoriaComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarAccionCombo", ReplyAction="http://tempuri.org/IService1/consultarAccionComboResponse")]
        TIENDA_YHM.Carlos.catAccion[] consultarAccionCombo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarAccionCombo", ReplyAction="http://tempuri.org/IService1/consultarAccionComboResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catAccion[]> consultarAccionComboAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacora", ReplyAction="http://tempuri.org/IService1/consultarBitacoraResponse")]
        TIENDA_YHM.Carlos.tblbitacora[] consultarBitacora();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacora", ReplyAction="http://tempuri.org/IService1/consultarBitacoraResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblbitacora[]> consultarBitacoraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacoraUsuario", ReplyAction="http://tempuri.org/IService1/consultarBitacoraUsuarioResponse")]
        TIENDA_YHM.Carlos.tblBitacorasUsuarios[] consultarBitacoraUsuario();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacoraUsuario", ReplyAction="http://tempuri.org/IService1/consultarBitacoraUsuarioResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblBitacorasUsuarios[]> consultarBitacoraUsuarioAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacoraCatalogo", ReplyAction="http://tempuri.org/IService1/consultarBitacoraCatalogoResponse")]
        TIENDA_YHM.Carlos.tblBitacorasCatalogos[] consultarBitacoraCatalogo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarBitacoraCatalogo", ReplyAction="http://tempuri.org/IService1/consultarBitacoraCatalogoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblBitacorasCatalogos[]> consultarBitacoraCatalogoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarSucural", ReplyAction="http://tempuri.org/IService1/consultarSucuralResponse")]
        TIENDA_YHM.Carlos.tblSucursal[] consultarSucural();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarSucural", ReplyAction="http://tempuri.org/IService1/consultarSucuralResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblSucursal[]> consultarSucuralAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarSucuralFinal", ReplyAction="http://tempuri.org/IService1/consultarSucuralFinalResponse")]
        TIENDA_YHM.Carlos.tblSucursal consultarSucuralFinal(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarSucuralFinal", ReplyAction="http://tempuri.org/IService1/consultarSucuralFinalResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblSucursal> consultarSucuralFinalAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarUsuarioUnico", ReplyAction="http://tempuri.org/IService1/consultarUsuarioUnicoResponse")]
        TIENDA_YHM.Carlos.tblUsuarios consultarUsuarioUnico(string _usuario, string _pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarUsuarioUnico", ReplyAction="http://tempuri.org/IService1/consultarUsuarioUnicoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblUsuarios> consultarUsuarioUnicoAsync(string _usuario, string _pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarCategoria", ReplyAction="http://tempuri.org/IService1/insertarCategoriaResponse")]
        bool insertarCategoria(string _strCategoria, bool _bitEstatus, int _idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarCategoria", ReplyAction="http://tempuri.org/IService1/insertarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> insertarCategoriaAsync(string _strCategoria, bool _bitEstatus, int _idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarUsuarios", ReplyAction="http://tempuri.org/IService1/insertarUsuariosResponse")]
        bool insertarUsuarios(string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarUsuarios", ReplyAction="http://tempuri.org/IService1/insertarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> insertarUsuariosAsync(string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarProductos", ReplyAction="http://tempuri.org/IService1/insertarProductosResponse")]
        bool insertarProductos(string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarProductos", ReplyAction="http://tempuri.org/IService1/insertarProductosResponse")]
        System.Threading.Tasks.Task<bool> insertarProductosAsync(string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacora", ReplyAction="http://tempuri.org/IService1/insertarBitacoraResponse")]
        bool insertarBitacora(int _idUsuario, string _strProductoViejo, string _strCategoriaViejo, string _strProductoNuevo, string _strCategoriaNuevo, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacora", ReplyAction="http://tempuri.org/IService1/insertarBitacoraResponse")]
        System.Threading.Tasks.Task<bool> insertarBitacoraAsync(int _idUsuario, string _strProductoViejo, string _strCategoriaViejo, string _strProductoNuevo, string _strCategoriaNuevo, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacoraUsuarios", ReplyAction="http://tempuri.org/IService1/insertarBitacoraUsuariosResponse")]
        bool insertarBitacoraUsuarios(int _idUsuario, string _strUsuarioViejo, string _strUsuarioNuevo, bool _bitCambioPass, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacoraUsuarios", ReplyAction="http://tempuri.org/IService1/insertarBitacoraUsuariosResponse")]
        System.Threading.Tasks.Task<bool> insertarBitacoraUsuariosAsync(int _idUsuario, string _strUsuarioViejo, string _strUsuarioNuevo, bool _bitCambioPass, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacoraCatalogo", ReplyAction="http://tempuri.org/IService1/insertarBitacoraCatalogoResponse")]
        bool insertarBitacoraCatalogo(int _idUsuario, string _strCatalogoViejo, string _strCatalogoNuevo, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/insertarBitacoraCatalogo", ReplyAction="http://tempuri.org/IService1/insertarBitacoraCatalogoResponse")]
        System.Threading.Tasks.Task<bool> insertarBitacoraCatalogoAsync(int _idUsuario, string _strCatalogoViejo, string _strCatalogoNuevo, int _idAccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarCategoria", ReplyAction="http://tempuri.org/IService1/eliminarCategoriaResponse")]
        bool eliminarCategoria(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarCategoria", ReplyAction="http://tempuri.org/IService1/eliminarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> eliminarCategoriaAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarUsuarios", ReplyAction="http://tempuri.org/IService1/eliminarUsuariosResponse")]
        bool eliminarUsuarios(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarUsuarios", ReplyAction="http://tempuri.org/IService1/eliminarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> eliminarUsuariosAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarProductos", ReplyAction="http://tempuri.org/IService1/eliminarProductosResponse")]
        bool eliminarProductos(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/eliminarProductos", ReplyAction="http://tempuri.org/IService1/eliminarProductosResponse")]
        System.Threading.Tasks.Task<bool> eliminarProductosAsync(int _id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarCategoria", ReplyAction="http://tempuri.org/IService1/editarCategoriaResponse")]
        bool editarCategoria(int _id, string _strCategoria, bool _bitEstatus, int _idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarCategoria", ReplyAction="http://tempuri.org/IService1/editarCategoriaResponse")]
        System.Threading.Tasks.Task<bool> editarCategoriaAsync(int _id, string _strCategoria, bool _bitEstatus, int _idSucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarUsuarios", ReplyAction="http://tempuri.org/IService1/editarUsuariosResponse")]
        bool editarUsuarios(int _id, string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarUsuarios", ReplyAction="http://tempuri.org/IService1/editarUsuariosResponse")]
        System.Threading.Tasks.Task<bool> editarUsuariosAsync(int _id, string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarProductos", ReplyAction="http://tempuri.org/IService1/editarProductosResponse")]
        bool editarProductos(int _id, string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/editarProductos", ReplyAction="http://tempuri.org/IService1/editarProductosResponse")]
        System.Threading.Tasks.Task<bool> editarProductosAsync(int _id, string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosEstatusResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductosEstatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosEstatusResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosEstatusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosNombreEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosNombreEstatusResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductosNombreEstatus(string _nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosNombreEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosNombreEstatusResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosNombreEstatusAsync(string _nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosCategoriaEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosCategoriaEstatusResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductosCategoriaEstatus(int _categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductosCategoriaEstatus", ReplyAction="http://tempuri.org/IService1/consultarProductosCategoriaEstatusResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosCategoriaEstatusAsync(int _categoria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductoEstatusInner", ReplyAction="http://tempuri.org/IService1/consultarProductoEstatusInnerResponse")]
        TIENDA_YHM.Carlos.tblProducto[] consultarProductoEstatusInner();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/consultarProductoEstatusInner", ReplyAction="http://tempuri.org/IService1/consultarProductoEstatusInnerResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductoEstatusInnerAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : TIENDA_YHM.Carlos.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<TIENDA_YHM.Carlos.IService1>, TIENDA_YHM.Carlos.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductos() {
            return base.Channel.consultarProductos();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosAsync() {
            return base.Channel.consultarProductosAsync();
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductosNombre(string _nombre) {
            return base.Channel.consultarProductosNombre(_nombre);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosNombreAsync(string _nombre) {
            return base.Channel.consultarProductosNombreAsync(_nombre);
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductosCategoria(int _categoria) {
            return base.Channel.consultarProductosCategoria(_categoria);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosCategoriaAsync(int _categoria) {
            return base.Channel.consultarProductosCategoriaAsync(_categoria);
        }
        
        public TIENDA_YHM.Carlos.tblUsuarios[] consultarUsuario() {
            return base.Channel.consultarUsuario();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblUsuarios[]> consultarUsuarioAsync() {
            return base.Channel.consultarUsuarioAsync();
        }
        
        public TIENDA_YHM.Carlos.catCategoria[] consultarCategoria() {
            return base.Channel.consultarCategoria();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catCategoria[]> consultarCategoriaAsync() {
            return base.Channel.consultarCategoriaAsync();
        }
        
        public TIENDA_YHM.Carlos.catCategoria[] consultarCategoriaCombo() {
            return base.Channel.consultarCategoriaCombo();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catCategoria[]> consultarCategoriaComboAsync() {
            return base.Channel.consultarCategoriaComboAsync();
        }
        
        public TIENDA_YHM.Carlos.catAccion[] consultarAccionCombo() {
            return base.Channel.consultarAccionCombo();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.catAccion[]> consultarAccionComboAsync() {
            return base.Channel.consultarAccionComboAsync();
        }
        
        public TIENDA_YHM.Carlos.tblbitacora[] consultarBitacora() {
            return base.Channel.consultarBitacora();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblbitacora[]> consultarBitacoraAsync() {
            return base.Channel.consultarBitacoraAsync();
        }
        
        public TIENDA_YHM.Carlos.tblBitacorasUsuarios[] consultarBitacoraUsuario() {
            return base.Channel.consultarBitacoraUsuario();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblBitacorasUsuarios[]> consultarBitacoraUsuarioAsync() {
            return base.Channel.consultarBitacoraUsuarioAsync();
        }
        
        public TIENDA_YHM.Carlos.tblBitacorasCatalogos[] consultarBitacoraCatalogo() {
            return base.Channel.consultarBitacoraCatalogo();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblBitacorasCatalogos[]> consultarBitacoraCatalogoAsync() {
            return base.Channel.consultarBitacoraCatalogoAsync();
        }
        
        public TIENDA_YHM.Carlos.tblSucursal[] consultarSucural() {
            return base.Channel.consultarSucural();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblSucursal[]> consultarSucuralAsync() {
            return base.Channel.consultarSucuralAsync();
        }
        
        public TIENDA_YHM.Carlos.tblSucursal consultarSucuralFinal(int _id) {
            return base.Channel.consultarSucuralFinal(_id);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblSucursal> consultarSucuralFinalAsync(int _id) {
            return base.Channel.consultarSucuralFinalAsync(_id);
        }
        
        public TIENDA_YHM.Carlos.tblUsuarios consultarUsuarioUnico(string _usuario, string _pass) {
            return base.Channel.consultarUsuarioUnico(_usuario, _pass);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblUsuarios> consultarUsuarioUnicoAsync(string _usuario, string _pass) {
            return base.Channel.consultarUsuarioUnicoAsync(_usuario, _pass);
        }
        
        public bool insertarCategoria(string _strCategoria, bool _bitEstatus, int _idSucursal) {
            return base.Channel.insertarCategoria(_strCategoria, _bitEstatus, _idSucursal);
        }
        
        public System.Threading.Tasks.Task<bool> insertarCategoriaAsync(string _strCategoria, bool _bitEstatus, int _idSucursal) {
            return base.Channel.insertarCategoriaAsync(_strCategoria, _bitEstatus, _idSucursal);
        }
        
        public bool insertarUsuarios(string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador) {
            return base.Channel.insertarUsuarios(_strUsuario, _strPass, _bitEstatus, _idSucursal, _bitAdministrador);
        }
        
        public System.Threading.Tasks.Task<bool> insertarUsuariosAsync(string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador) {
            return base.Channel.insertarUsuariosAsync(_strUsuario, _strPass, _bitEstatus, _idSucursal, _bitAdministrador);
        }
        
        public bool insertarProductos(string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora) {
            return base.Channel.insertarProductos(_strProducto, _idSucursal, _intCantidad, _bitEstatus, _idCategora);
        }
        
        public System.Threading.Tasks.Task<bool> insertarProductosAsync(string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora) {
            return base.Channel.insertarProductosAsync(_strProducto, _idSucursal, _intCantidad, _bitEstatus, _idCategora);
        }
        
        public bool insertarBitacora(int _idUsuario, string _strProductoViejo, string _strCategoriaViejo, string _strProductoNuevo, string _strCategoriaNuevo, int _idAccion) {
            return base.Channel.insertarBitacora(_idUsuario, _strProductoViejo, _strCategoriaViejo, _strProductoNuevo, _strCategoriaNuevo, _idAccion);
        }
        
        public System.Threading.Tasks.Task<bool> insertarBitacoraAsync(int _idUsuario, string _strProductoViejo, string _strCategoriaViejo, string _strProductoNuevo, string _strCategoriaNuevo, int _idAccion) {
            return base.Channel.insertarBitacoraAsync(_idUsuario, _strProductoViejo, _strCategoriaViejo, _strProductoNuevo, _strCategoriaNuevo, _idAccion);
        }
        
        public bool insertarBitacoraUsuarios(int _idUsuario, string _strUsuarioViejo, string _strUsuarioNuevo, bool _bitCambioPass, int _idAccion) {
            return base.Channel.insertarBitacoraUsuarios(_idUsuario, _strUsuarioViejo, _strUsuarioNuevo, _bitCambioPass, _idAccion);
        }
        
        public System.Threading.Tasks.Task<bool> insertarBitacoraUsuariosAsync(int _idUsuario, string _strUsuarioViejo, string _strUsuarioNuevo, bool _bitCambioPass, int _idAccion) {
            return base.Channel.insertarBitacoraUsuariosAsync(_idUsuario, _strUsuarioViejo, _strUsuarioNuevo, _bitCambioPass, _idAccion);
        }
        
        public bool insertarBitacoraCatalogo(int _idUsuario, string _strCatalogoViejo, string _strCatalogoNuevo, int _idAccion) {
            return base.Channel.insertarBitacoraCatalogo(_idUsuario, _strCatalogoViejo, _strCatalogoNuevo, _idAccion);
        }
        
        public System.Threading.Tasks.Task<bool> insertarBitacoraCatalogoAsync(int _idUsuario, string _strCatalogoViejo, string _strCatalogoNuevo, int _idAccion) {
            return base.Channel.insertarBitacoraCatalogoAsync(_idUsuario, _strCatalogoViejo, _strCatalogoNuevo, _idAccion);
        }
        
        public bool eliminarCategoria(int _id) {
            return base.Channel.eliminarCategoria(_id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarCategoriaAsync(int _id) {
            return base.Channel.eliminarCategoriaAsync(_id);
        }
        
        public bool eliminarUsuarios(int _id) {
            return base.Channel.eliminarUsuarios(_id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarUsuariosAsync(int _id) {
            return base.Channel.eliminarUsuariosAsync(_id);
        }
        
        public bool eliminarProductos(int _id) {
            return base.Channel.eliminarProductos(_id);
        }
        
        public System.Threading.Tasks.Task<bool> eliminarProductosAsync(int _id) {
            return base.Channel.eliminarProductosAsync(_id);
        }
        
        public bool editarCategoria(int _id, string _strCategoria, bool _bitEstatus, int _idSucursal) {
            return base.Channel.editarCategoria(_id, _strCategoria, _bitEstatus, _idSucursal);
        }
        
        public System.Threading.Tasks.Task<bool> editarCategoriaAsync(int _id, string _strCategoria, bool _bitEstatus, int _idSucursal) {
            return base.Channel.editarCategoriaAsync(_id, _strCategoria, _bitEstatus, _idSucursal);
        }
        
        public bool editarUsuarios(int _id, string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador) {
            return base.Channel.editarUsuarios(_id, _strUsuario, _strPass, _bitEstatus, _idSucursal, _bitAdministrador);
        }
        
        public System.Threading.Tasks.Task<bool> editarUsuariosAsync(int _id, string _strUsuario, string _strPass, bool _bitEstatus, int _idSucursal, bool _bitAdministrador) {
            return base.Channel.editarUsuariosAsync(_id, _strUsuario, _strPass, _bitEstatus, _idSucursal, _bitAdministrador);
        }
        
        public bool editarProductos(int _id, string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora) {
            return base.Channel.editarProductos(_id, _strProducto, _idSucursal, _intCantidad, _bitEstatus, _idCategora);
        }
        
        public System.Threading.Tasks.Task<bool> editarProductosAsync(int _id, string _strProducto, int _idSucursal, int _intCantidad, bool _bitEstatus, int _idCategora) {
            return base.Channel.editarProductosAsync(_id, _strProducto, _idSucursal, _intCantidad, _bitEstatus, _idCategora);
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductosEstatus() {
            return base.Channel.consultarProductosEstatus();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosEstatusAsync() {
            return base.Channel.consultarProductosEstatusAsync();
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductosNombreEstatus(string _nombre) {
            return base.Channel.consultarProductosNombreEstatus(_nombre);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosNombreEstatusAsync(string _nombre) {
            return base.Channel.consultarProductosNombreEstatusAsync(_nombre);
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductosCategoriaEstatus(int _categoria) {
            return base.Channel.consultarProductosCategoriaEstatus(_categoria);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductosCategoriaEstatusAsync(int _categoria) {
            return base.Channel.consultarProductosCategoriaEstatusAsync(_categoria);
        }
        
        public TIENDA_YHM.Carlos.tblProducto[] consultarProductoEstatusInner() {
            return base.Channel.consultarProductoEstatusInner();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.Carlos.tblProducto[]> consultarProductoEstatusInnerAsync() {
            return base.Channel.consultarProductoEstatusInnerAsync();
        }
    }
}
