//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENDA_YHM.ServiceTiendaDEJ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContrasenaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contrasena {
            get {
                return this.ContrasenaField;
            }
            set {
                if ((object.ReferenceEquals(this.ContrasenaField, value) != true)) {
                    this.ContrasenaField = value;
                    this.RaisePropertyChanged("Contrasena");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario {
            get {
                return this.IdUsuarioField;
            }
            set {
                if ((this.IdUsuarioField.Equals(value) != true)) {
                    this.IdUsuarioField = value;
                    this.RaisePropertyChanged("IdUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTiendaDEJ.IServiceTiendaDEJ")]
    public interface IServiceTiendaDEJ {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetProducto", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetProductoResponse")]
        TIENDA_YHM.ServiceTiendaDEJ.Producto[] GetProducto(int idsurcusal, string productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetProducto", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetProductoResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Producto[]> GetProductoAsync(int idsurcusal, string productos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetUsuario", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetUsuarioResponse")]
        TIENDA_YHM.ServiceTiendaDEJ.Usuario GetUsuario(string user, int idsucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetUsuario", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetUsuarioResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Usuario> GetUsuarioAsync(string user, int idsucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetProductos", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetProductosResponse")]
        TIENDA_YHM.ServiceTiendaDEJ.Producto[] GetProductos(int idsucursal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceTiendaDEJ/GetProductos", ReplyAction="http://tempuri.org/IServiceTiendaDEJ/GetProductosResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Producto[]> GetProductosAsync(int idsucursal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceTiendaDEJChannel : TIENDA_YHM.ServiceTiendaDEJ.IServiceTiendaDEJ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceTiendaDEJClient : System.ServiceModel.ClientBase<TIENDA_YHM.ServiceTiendaDEJ.IServiceTiendaDEJ>, TIENDA_YHM.ServiceTiendaDEJ.IServiceTiendaDEJ {
        
        public ServiceTiendaDEJClient() {
        }
        
        public ServiceTiendaDEJClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceTiendaDEJClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTiendaDEJClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceTiendaDEJClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TIENDA_YHM.ServiceTiendaDEJ.Producto[] GetProducto(int idsurcusal, string productos) {
            return base.Channel.GetProducto(idsurcusal, productos);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Producto[]> GetProductoAsync(int idsurcusal, string productos) {
            return base.Channel.GetProductoAsync(idsurcusal, productos);
        }
        
        public TIENDA_YHM.ServiceTiendaDEJ.Usuario GetUsuario(string user, int idsucursal) {
            return base.Channel.GetUsuario(user, idsucursal);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Usuario> GetUsuarioAsync(string user, int idsucursal) {
            return base.Channel.GetUsuarioAsync(user, idsucursal);
        }
        
        public TIENDA_YHM.ServiceTiendaDEJ.Producto[] GetProductos(int idsucursal) {
            return base.Channel.GetProductos(idsucursal);
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.ServiceTiendaDEJ.Producto[]> GetProductosAsync(int idsucursal) {
            return base.Channel.GetProductosAsync(idsucursal);
        }
    }
}
