//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIENDA_YHM.ServSucJNJ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegProducto", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaJNJCliente")]
    [System.SerializableAttribute()]
    public partial class RegProducto : TIENDA_YHM.ServSucJNJ.BaseRespuesta {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BitEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CantidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCategoriaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdSucursalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomProductoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BitEstatus {
            get {
                return this.BitEstatusField;
            }
            set {
                if ((this.BitEstatusField.Equals(value) != true)) {
                    this.BitEstatusField = value;
                    this.RaisePropertyChanged("BitEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Cantidad {
            get {
                return this.CantidadField;
            }
            set {
                if ((this.CantidadField.Equals(value) != true)) {
                    this.CantidadField = value;
                    this.RaisePropertyChanged("Cantidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCategoria {
            get {
                return this.IdCategoriaField;
            }
            set {
                if ((this.IdCategoriaField.Equals(value) != true)) {
                    this.IdCategoriaField = value;
                    this.RaisePropertyChanged("IdCategoria");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdSucursal {
            get {
                return this.IdSucursalField;
            }
            set {
                if ((this.IdSucursalField.Equals(value) != true)) {
                    this.IdSucursalField = value;
                    this.RaisePropertyChanged("IdSucursal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomProducto {
            get {
                return this.NomProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.NomProductoField, value) != true)) {
                    this.NomProductoField = value;
                    this.RaisePropertyChanged("NomProducto");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WCFTiendaJNJCliente")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TIENDA_YHM.ServSucJNJ.RegProducto))]
    public partial class BaseRespuesta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeRespuestaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeRespuesta {
            get {
                return this.MensajeRespuestaField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeRespuestaField, value) != true)) {
                    this.MensajeRespuestaField = value;
                    this.RaisePropertyChanged("MensajeRespuesta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServSucJNJ.IServConsulCliente")]
    public interface IServConsulCliente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServConsulCliente/verifRegLogin", ReplyAction="http://tempuri.org/IServConsulCliente/verifRegLoginResponse")]
        bool verifRegLogin(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServConsulCliente/verifRegLogin", ReplyAction="http://tempuri.org/IServConsulCliente/verifRegLoginResponse")]
        System.Threading.Tasks.Task<bool> verifRegLoginAsync(string usuario, string pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServConsulCliente/consulProductos", ReplyAction="http://tempuri.org/IServConsulCliente/consulProductosResponse")]
        TIENDA_YHM.ServSucJNJ.RegProducto[] consulProductos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServConsulCliente/consulProductos", ReplyAction="http://tempuri.org/IServConsulCliente/consulProductosResponse")]
        System.Threading.Tasks.Task<TIENDA_YHM.ServSucJNJ.RegProducto[]> consulProductosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServConsulClienteChannel : TIENDA_YHM.ServSucJNJ.IServConsulCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServConsulClienteClient : System.ServiceModel.ClientBase<TIENDA_YHM.ServSucJNJ.IServConsulCliente>, TIENDA_YHM.ServSucJNJ.IServConsulCliente {
        
        public ServConsulClienteClient() {
        }
        
        public ServConsulClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServConsulClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServConsulClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServConsulClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool verifRegLogin(string usuario, string pass) {
            return base.Channel.verifRegLogin(usuario, pass);
        }
        
        public System.Threading.Tasks.Task<bool> verifRegLoginAsync(string usuario, string pass) {
            return base.Channel.verifRegLoginAsync(usuario, pass);
        }
        
        public TIENDA_YHM.ServSucJNJ.RegProducto[] consulProductos() {
            return base.Channel.consulProductos();
        }
        
        public System.Threading.Tasks.Task<TIENDA_YHM.ServSucJNJ.RegProducto[]> consulProductosAsync() {
            return base.Channel.consulProductosAsync();
        }
    }
}
